server:
  port: 5002
  tomcat:
    max-threads: 1500
    min-spare-threads: 150
spring:
  application:
    name: tsmd-aras
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
ribbon:
  eureka:
    enabled: false
api.key: 044e881a7058ef54b5b7fc754a30c36f
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
