server:
  port: 5009
  tomcat:
    max-threads: 1500
    min-spare-threads: 150
spring:
  application:
    name: tsmd-common
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://172.19.0.9:8761/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/