server:
  port: 8761
eureka:
  client:
    # eureka by default will register itself as a client. So, we need to set it to false.
    # What's a client server? See other microservices (student, auth, etc).
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-server