server:
  port: 5001
  tomcat:
    max-threads: 1500
    min-spare-threads: 150
spring:
  application:
    name: tsmd-cengiz
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB
      max-request-size: 8MB
  mail:
    host: 10.10.50.14
    username: test
    password: 1qaz2wsX!
    port: 587
    properties:
      mail:
        debug: true
        transport.protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: false
          starttls:
            enable: false
    test-connection: false
  datasource:
    hikari:
      username: postgres
      password: MYPASSWD
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 20500
    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://tsmd-postgres:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#logging.file: logs/tsmd-cengiz/app.log # spring 2.0.0 da file ve max-size propertylerini birlikte bu şekilde set edebiliyoruz.
#logging.pattern.console:
#logging:
#  file:
#    max-size: 50MB
#  level:
#    ROOT: ERROR
#    tr.com: INFO
logging:
  level:
    root: info
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eureka:8761/eureka/
